export const ACTION_TYPES = {
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  SET_TO_ZERO_FETCH_COUNTER: "SET_TO_ZERO_FETCH_COUNTER",
  INCREASE_FETCH_COUNTER: "INCREASE_FETCH_COUNTER",
  SET_WEIGHT_VALUE: "SET_WEIGHT_VALUE",
  CHANGE_INPUT: "CHANGE_INPUT",
};

export const COURIER_NAMES = {
  PARCEL2GO: "PARCEL2GO",
  PARCEL_MONKEY: "PARCEL_MONKEY",
};

export const VARIABLES = {
  SLOW: "SLOW",
  MEDIUM: "MEDIUM",
  FAST: "FAST",
  SMALL: "SMALL",
  LARGE: "LARGE",
  ALL: "ALL",
  VALUE: "VALUE",
  WEIGHT: "WEIGHT",
  LENGTH: "LENGTH",
  WIDTH: "WIDTH",
  HEIGHT: "HEIGHT",
};
