export const ACTION_TYPES = {
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
};

export const COURIER_NAMES = {
  PARCEL2GO: "PARCEL2GO",
  PARCEL_MONKEY: "PARCEL_MONKEY",
};

export const VARIABLES = {
  SLOW: "SLOW",
  MEDIUM: "MEDIUM",
  FAST: "FAST",
  SMALL: "SMALL",
  LARGE: "LARGE",
  ALL: "ALL",
};
