module.exports = {
  ACTION_TYPES: {
    FETCH_START: "FETCH_START",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR",
  },
  COURIER_NAMES: {
    PARCEL2GO: "PARCEL2GO",
    PARCEL_MONKEY: "PARCEL_MONKEY",
  },
  VARIABLES: {
    SLOW: "SLOW",
    MEDIUM: "MEDIUM",
    FAST: "FAST",
  },
};
