interface variables {
  PARCEL2GO: string,
  PARCEL_MONKEY: string,
  SLOW: string,
  MEDIUM: string,
  FAST: string,
  SMALL: string,
  LARGE: string,
  ALL: string,
  VALUE: string,
  WEIGHT: string,
  LENGTH: string,
  WIDTH: string,
  HEIGHT: string,
}

export const VARIABLES: variables = {
  PARCEL2GO: "PARCEL2GO",
  PARCEL_MONKEY: "PARCEL_MONKEY",
  SLOW: "SLOW",
  MEDIUM: "MEDIUM",
  FAST: "FAST",
  SMALL: "SMALL",
  LARGE: "LARGE",
  ALL: "ALL",
  VALUE: "VALUE",
  WEIGHT: "WEIGHT",
  LENGTH: "LENGTH",
  WIDTH: "WIDTH",
  HEIGHT: "HEIGHT",
};
